# Generated by Django 4.2.4 on 2023-08-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='sucursalesT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=40)),
                ('cuit', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('instagram', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='localidad',
        ),
        migrations.DeleteModel(
            name='sucursales',
        ),
    ]
