# Generated by Django 4.2.4 on 2023-09-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sucursalest_delete_localidad_delete_sucursales'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('estilo', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=15)),
                ('talle', models.IntegerField()),
            ],
        ),
    ]
