# Generated by Django 4.2.4 on 2023-09-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sucursalesT',
            new_name='sucursales',
        ),
    ]
