# Generated by Django 4.2.5 on 2023-10-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_clientes_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='personalLocal',
            new_name='Personal',
        ),
        migrations.DeleteModel(
            name='clientes',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='talle',
            new_name='precio',
        ),
    ]
