# Generated by Django 4.2.5 on 2023-11-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cliente_rename_personallocal_personal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('mensaje', models.CharField(max_length=350)),
            ],
        ),
    ]
