# Generated by Django 4.2.5 on 2023-11-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_body_comment_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
